databases:
  - name: comolor-pos-db
    databaseName: comolor_pos
    user: comolor_admin
    region: oregon
    plan: free

services:
  - type: web
    name: comolor-pos
    runtime: python3
    region: oregon
    plan: free
    buildCommand: pip install --upgrade pip setuptools wheel && pip install -r render-python313-requirements.txt
    startCommand: gunicorn --bind 0.0.0.0:$PORT --workers 1 --timeout 120 --max-requests 1000 --max-requests-jitter 100 main:app
    envVars:
      - key: DATABASE_URL
        fromDatabase:
          name: comolor-pos-db
          property: connectionString
      - key: SESSION_SECRET
        generateValue: true
      - key: SECRET_KEY
        generateValue: true
      - key: PYTHON_VERSION
        value: "3.11"
      - key: FLASK_ENV
        value: production
      - key: MPESA_ENVIRONMENT
        value: sandbox
    healthCheckPath: /
    autoDeploy: true
    disk:
      name: comolor-uploads
      mountPath: /tmp/uploads
      sizeGB: 1